<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Services.WebApi.Interface\Services.WebApi.Interface.csproj" />
    <ProjectReference Include="..\WebApi.Data\WebApi.Data.csproj" />
    <ProjectReference Include="..\WebApi.Model\WebApi.Model.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
